server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver